# Código ATUALIZADO para o arquivo: application.yml
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/mini_mundo_db
    username: minimundo_user
    password: minimundo_pwd
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    mongodb:
      uri: mongodb://localhost:27017/mini_mundo_db
    redis:
      host: localhost
      port: 6379

  # Configuração para o upload de arquivos via multipart
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080

# <<< SEÇÃO DE CONFIGURAÇÃO DO MINIO ADICIONADA AQUI >>>
minio:
  url: http://localhost:9000
  accessKey: minio_admin
  secretKey: minio_password
  bucketName: produtos